#pragma once

#include <stdint.h>
#include "PlantLogic.h"

namespace plant8 {

constexpr uint8_t PLANT_COUNT = 8;
constexpr uint8_t MUX_CAPACITY = 16;
constexpr uint16_t CONFIG_VERSION = 4;

struct PlantConfig {
  char name[24];
  uint8_t muxChannel;
  bool enabled;
  bool calibrated;
  uint16_t dryRaw;
  uint16_t wetRaw;
  Thresholds thresholds;
};

struct DeviceConfig {
  uint16_t version;
  char wifiSsid[33];
  char wifiPassword[65];
  // Runtime token generated by the PlatIO mobile app. It is stored only on the device,
  // never hard-coded into firmware or committed to GitHub.
  char expoPushToken[192];
  PlantConfig plants[PLANT_COUNT];
};

struct PlantRuntime {
  uint16_t raw = 0;
  float percent = -1.0f;
  float emaPercent = -1.0f;
  RuntimeState logic;
  bool sensorHealthy = true;
  bool alertSent = false;
};

} // namespace plant8
